'use server'

import { verifySession } from "@/lib/session"
import { db } from "@/lib/db"
import { redirect } from "next/navigation"

export async function getAdminMetrics() {
    const session = await verifySession()
    if (!session || session.role !== 'ADMIN') {
        redirect('/dashboard')
    }

    try {
        // Parallelize queries for performance
        const [
            totalUsers,
            trialUsers,
            activeSubs,
            verifiedUsers,
            totalInvoices,
            totalRevenue,
            platformRev,
            priceSetting
        ] = await Promise.all([
            // 1. Total Users
            db.user.count(),

            // 2. Users in Trial
            db.user.count({ where: { subscriptionStatus: 'trial' } }),

            // 3. Active Subscriptions (paying)
            db.user.count({ where: { subscriptionStatus: 'active' } }),

            // 4. Verified Emails
            db.user.count({ where: { isEmailVerified: true } }),

            // 5. Total Invoices (All users)
            db.invoice.count(),

            // 6. Total Revenue (Approximate sum of all invoices)
            db.invoice.aggregate({
                _sum: { totalAmount: true },
                where: { cae: { not: null } }
            }),

            // 7. Platform Revenue (Real money collected from subscriptions)
            db.subscriptionPayment.aggregate({
                _sum: { amount: true },
                where: { status: 'approved' }
            }),

            // 8. Get current subscription price for MRR
            db.systemSetting.findUnique({
                where: { key: 'SUBSCRIPTION_PRICE' }
            })
        ])

        const currentPrice = Number(priceSetting?.value || 25000)
        const activeSubsCount = activeSubs
        const estimatedMRR = activeSubsCount * currentPrice

        return {
            totalUsers,
            trialUsers,
            activeSubs,
            verifiedUsers,
            totalInvoices,
            totalInvoiceRevenue: Number(totalRevenue._sum.totalAmount || 0), // Revenue generated BY users (billing)
            platformRevenue: Number(platformRev._sum.amount || 0), // Revenue generated FOR platform
            mrr: estimatedMRR
        }

    } catch (error) {
        console.error("Error fetching admin metrics:", error)
        return null
    }
}
